EXERCISE_PLANE_EMPTY = 'нет'
EXERCISE_PLANE_TREADMILL = 'беговая'
EXERCISE_PLANE_PILATES = 'растягивания'
EXERCISE_PLANE_BOOTHS = 'оба'

EXERCISES = [EXERCISE_PLANE_EMPTY, EXERCISE_PLANE_TREADMILL, EXERCISE_PLANE_PILATES, EXERCISE_PLANE_BOOTHS]
