NOTIFICATION_EVENT_REGULAR_NOT_STARTED = 'notification_event_regular_not_started'
NOTIFICATION_MESSAGE = 'notification_message'
NOTIFICATION_QUESTION = 'notification_question'

BUTTON_VARIANT_SUCCESS = 'success'
BUTTON_VARIANT_WARNING = 'warning'
BUTTON_VARIANT_DANGER = 'danger'
BUTTON_VARIANT_INFO = 'info'
BUTTON_VARIANT_PRIMARY = 'primary'
BUTTON_VARIANT_SECONDARY = 'secondary'
